# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 671, 511))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.start_btn = QtWidgets.QPushButton(self.tab)
        self.start_btn.setGeometry(QtCore.QRect(570, 430, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.status_scroll = QtWidgets.QScrollArea(self.tab)
        self.status_scroll.setGeometry(QtCore.QRect(0, 0, 661, 431))
        self.status_scroll.setMinimumSize(QtCore.QSize(0, 0))
        self.status_scroll.setWidgetResizable(True)
        self.status_scroll.setObjectName("status_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 429))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.status_print = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.status_print.setEnabled(True)
        self.status_print.setGeometry(QtCore.QRect(0, 0, 661, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.status_print.setFont(font)
        self.status_print.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.status_print.setMouseTracking(True)
        self.status_print.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.status_print.setObjectName("status_print")
        self.status_scroll.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.save_btn = QtWidgets.QPushButton(self.tab_2)
        self.save_btn.setGeometry(QtCore.QRect(510, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.username_label = QtWidgets.QLabel(self.tab_2)
        self.username_label.setGeometry(QtCore.QRect(60, 30, 121, 21))
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.tab_2)
        self.password_label.setGeometry(QtCore.QRect(60, 180, 111, 21))
        self.password_label.setObjectName("password_label")
        self.password_text = QtWidgets.QTextEdit(self.tab_2)
        self.password_text.setGeometry(QtCore.QRect(10, 210, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.password_text.setFont(font)
        self.password_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.password_text.setObjectName("password_text")
        self.inventory_id_label = QtWidgets.QLabel(self.tab_2)
        self.inventory_id_label.setGeometry(QtCore.QRect(50, 340, 141, 21))
        self.inventory_id_label.setObjectName("inventory_id_label")
        self.inventory_id_text = QtWidgets.QTextEdit(self.tab_2)
        self.inventory_id_text.setGeometry(QtCore.QRect(10, 370, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.inventory_id_text.setFont(font)
        self.inventory_id_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.inventory_id_text.setObjectName("inventory_id_text")
        self.game_list_label = QtWidgets.QLabel(self.tab_2)
        self.game_list_label.setGeometry(QtCore.QRect(420, 10, 91, 31))
        self.game_list_label.setObjectName("game_list_label")
        self.username_text = QtWidgets.QTextEdit(self.tab_2)
        self.username_text.setEnabled(True)
        self.username_text.setGeometry(QtCore.QRect(10, 60, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.username_text.setFont(font)
        self.username_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username_text.setObjectName("username_text")
        self.remove_btn = QtWidgets.QPushButton(self.tab_2)
        self.remove_btn.setGeometry(QtCore.QRect(410, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.remove_btn.setFont(font)
        self.remove_btn.setObjectName("remove_btn")
        self.add_btn = QtWidgets.QPushButton(self.tab_2)
        self.add_btn.setGeometry(QtCore.QRect(310, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_btn.setFont(font)
        self.add_btn.setObjectName("add_btn")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(250, 60, 411, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.checkbox_vlayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.checkbox_vlayout.setContentsMargins(0, 0, 0, 0)
        self.checkbox_vlayout.setObjectName("checkbox_vlayout")
        self.checkbox_scroll = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_scroll.setFont(font)
        self.checkbox_scroll.setWidgetResizable(True)
        self.checkbox_scroll.setObjectName("checkbox_scroll")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 407, 347))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.checkbox_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.checkbox_vlayout.addWidget(self.checkbox_scroll)
        self.game_list_label_2 = QtWidgets.QLabel(self.tab_2)
        self.game_list_label_2.setGeometry(QtCore.QRect(410, 30, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.game_list_label_2.setFont(font)
        self.game_list_label_2.setObjectName("game_list_label_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoBooster"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.status_print.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.save_btn.setText(_translate("MainWindow", "Save config"))
        self.username_label.setText(_translate("MainWindow", "Username : "))
        self.password_label.setText(_translate("MainWindow", "Password : "))
        self.password_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">  </span></p></body></html>"))
        self.inventory_id_label.setText(_translate("MainWindow", "Inventory ID : "))
        self.inventory_id_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\"> </span></p></body></html>"))
        self.game_list_label.setText(_translate("MainWindow", "App list :"))
        self.username_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\"> </span></p></body></html>"))
        self.remove_btn.setText(_translate("MainWindow", "Remove app"))
        self.add_btn.setText(_translate("MainWindow", "Add app"))
        self.game_list_label_2.setText(_translate("MainWindow", "(Select for remove)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Config"))

